<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VictimSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('victims')->insert([
            // 1st case - Ted Bundy
            [
                'killer_id' => 1,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'Lynda Ann Healy',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'University Student',
                            'education' => 'University of Washington',
                            'location' => 'Seattle, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'February 1, 1974',
                            'case_connection' => 'A University of Washington student who disappeared from her shared home and became Ted Bundy\'s first confirmed murder victim.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Donna Gail Manson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'College Student',
                            'education' => 'Evergreen State College',
                            'location' => 'Olympia, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'March 12, 1974',
                            'case_connection' => 'An Evergreen State College student who disappeared while walking to a jazz concert. Her body has never been conclusively recovered.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Susan Elaine Rancourt',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'College Student',
                            'education' => 'Central Washington State College',
                            'location' => 'Ellensburg, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'April 17, 1974',
                            'case_connection' => 'A Central Washington State College student who disappeared after attending an evening class.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Roberta Kathleen Parks',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'College Student',
                            'education' => 'Oregon State University',
                            'location' => 'Corvallis, Oregon',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 6, 1974',
                            'case_connection' => 'An Oregon State University student who vanished while walking to her dormitory.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Brenda Carol Ball',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Burien, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 1, 1974',
                            'case_connection' => 'Disappeared after leaving a local tavern. Her remains were later discovered on Taylor Mountain.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Georgann Hawkins',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'University Student',
                            'education' => 'University of Washington',
                            'location' => 'Seattle, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 11, 1974',
                            'case_connection' => 'A University of Washington student abducted while walking through an alley near her sorority house.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Janice Ann Ott',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 23,
                            'occupation' => 'Probation Caseworker',
                            'education' => null,
                            'location' => 'Lake Sammamish, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 14, 1974',
                            'case_connection' => 'Abducted from Lake Sammamish State Park after being approached by a man introducing himself as "Ted."',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Denise Marie Naslund',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'College Student',
                            'education' => null,
                            'location' => 'Lake Sammamish, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 14, 1974',
                            'case_connection' => 'Kidnapped from Lake Sammamish State Park only hours after Janice Ott disappeared.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Nancy Wilcox',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Holladay, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 2, 1974',
                            'case_connection' => 'Disappeared while walking home. Bundy later confessed to her murder.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Melissa Anne Smith',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Midvale, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 18, 1974',
                            'case_connection' => 'The daughter of a local police chief who disappeared after leaving a pizza restaurant.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Laura Ann Aime',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Lehi, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 31, 1974',
                            'case_connection' => 'Last seen after leaving a Halloween party. DNA evidence later confirmed Bundy as her killer.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Debra Jean Kent',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Bountiful, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'November 8, 1974',
                            'case_connection' => 'Disappeared after leaving a school play. Only small remains were ever recovered.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Caryn Eileen Campbell',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 23,
                            'occupation' => 'Registered Nurse',
                            'education' => null,
                            'location' => 'Snowmass, Colorado',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 12, 1975',
                            'case_connection' => 'Disappeared from a ski resort hotel while on vacation with her fiancé.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Julie Lyle Cunningham',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 26,
                            'occupation' => 'Ski Resort Employee',
                            'education' => null,
                            'location' => 'Vail, Colorado',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'March 15, 1975',
                            'case_connection' => 'Vanished while walking to her apartment after work. Her body has never been recovered.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Denise Lynn Oliverson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 24,
                            'occupation' => 'Administrative Assistant',
                            'education' => null,
                            'location' => 'Grand Junction, Colorado',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'April 6, 1975',
                            'case_connection' => 'Disappeared while riding her bicycle to her parents\' home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Lynnette Dawn Culver',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 12,
                            'occupation' => 'Middle School Student',
                            'education' => null,
                            'location' => 'Pocatello, Idaho',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 6, 1975',
                            'case_connection' => 'Abducted from her school grounds. Bundy later confessed to her murder.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Susan Curtis',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Provo, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 28, 1975',
                            'case_connection' => 'Disappeared after attending a youth conference at Brigham Young University.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Margaret Elizabeth Bowman',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'University Student',
                            'education' => 'Florida State University',
                            'location' => 'Tallahassee, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 15, 1978',
                            'case_connection' => 'One of two Florida State University students murdered during Bundy\'s attack on the Chi Omega sorority house.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Lisa Janet Levy',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'University Student',
                            'education' => 'Florida State University',
                            'location' => 'Tallahassee, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 15, 1978',
                            'case_connection' => 'Killed during the Chi Omega sorority house attack that led to Bundy\'s eventual conviction.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Kimberly Dianne Leach',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 12,
                            'occupation' => 'Middle School Student',
                            'education' => null,
                            'location' => 'Lake City, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'February 9, 1978',
                            'case_connection' => 'Abducted from her school and became Bundy\'s final confirmed victim before his arrest.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],

                    'wounded' => [
                        [
                            'name' => 'Karen Sparks',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'University Student',
                            'education' => 'University of Washington',
                            'location' => 'Seattle, Washington',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 4, 1974',
                            'case_connection' => 'Survived a brutal assault in her home but suffered permanent brain injuries.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Carol DaRonch',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Murray, Utah',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'November 8, 1974',
                            'case_connection' => 'Escaped after Bundy impersonated a police officer and attempted to kidnap her.',
                            'legacy' => 'Her testimony later played an important role in Bundy\'s conviction.',
                            'image' => null,
                        ],
                        [
                            'name' => 'Karen Chandler',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'University Student',
                            'education' => 'Florida State University',
                            'location' => 'Tallahassee, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 15, 1978',
                            'case_connection' => 'Seriously injured during Bundy\'s attack inside the Chi Omega sorority house.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Kathy Kleiner',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'University Student',
                            'education' => 'Florida State University',
                            'location' => 'Tallahassee, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 15, 1978',
                            'case_connection' => 'Survived severe injuries during the Chi Omega attack.',
                            'legacy' => 'Later became an advocate for victims.',
                            'image' => null,
                        ],
                        [
                            'name' => 'Cheryl Thomas',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'University Student',
                            'education' => 'Florida State University',
                            'location' => 'Tallahassee, Florida',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 15, 1978',
                            'case_connection' => 'Attacked in her apartment shortly after the Chi Omega murders and survived with serious injuries.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],
                ])
            ],

            // 2nd case - Zodiac Killer
            [
                'killer_id' => 2,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'David Arthur Faraday',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Benicia, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 20, 1968',
                            'case_connection' => 'A high school student who was shot while on his first date with Betty Lou Jensen near Lake Herman Road.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Betty Lou Jensen',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Benicia, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 20, 1968',
                            'case_connection' => 'Killed while attempting to flee from the attacker during the Lake Herman Road shootings.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Darlene Elizabeth Ferrin',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Restaurant Waitress',
                            'education' => null,
                            'location' => 'Vallejo, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 5, 1969',
                            'case_connection' => 'Shot multiple times while parked with Michael Mageau at Blue Rock Springs Park. She later died from her injuries.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Cecelia Ann Shepard',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'University Student',
                            'education' => null,
                            'location' => 'Lake Berryessa, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 27, 1969',
                            'case_connection' => 'Attacked while picnicking with Bryan Hartnell. She died two days later from her injuries.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Paul Lee Stine',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 29,
                            'occupation' => 'Taxi Driver',
                            'education' => null,
                            'location' => 'San Francisco, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 11, 1969',
                            'case_connection' => 'A taxi driver who was fatally shot during an attack in San Francisco.',
                            'legacy' => 'His murder produced some of the most detailed eyewitness descriptions associated with the Zodiac investigation.',
                            'image' => null,
                        ],
                    ],

                    'wounded' => [
                        [
                            'name' => 'Michael Renault Mageau',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Restaurant Worker',
                            'education' => null,
                            'location' => 'Vallejo, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 5, 1969',
                            'case_connection' => 'Survived the Blue Rock Springs attack despite being shot multiple times.',
                            'legacy' => 'He later provided investigators with a description of the attacker.',
                            'image' => null,
                        ],
                        [
                            'name' => 'Bryan Calvin Hartnell',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'University Student',
                            'education' => null,
                            'location' => 'Lake Berryessa, California',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 27, 1969',
                            'case_connection' => 'Survived a stabbing attack at Lake Berryessa.',
                            'legacy' => 'He gave investigators one of the most detailed firsthand accounts of the Zodiac Killer.',
                            'image' => null,
                        ],
                    ],
                ])
            ],

            // 3rd case - Jack the Ripper
            [
                'killer_id' => 3,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'Mary Ann Nichols',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 43,
                            'occupation' => 'Domestic Servant',
                            'education' => null,
                            'location' => 'Whitechapel, London, England',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'August 31, 1888',
                            'case_connection' => 'Known as "Polly," Nichols is widely regarded as the first of Jack the Ripper\'s five canonical victims. She had experienced homelessness and financial hardship before her murder.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Annie Chapman',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 47,
                            'occupation' => 'Domestic Servant',
                            'education' => null,
                            'location' => 'Whitechapel, London, England',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 8, 1888',
                            'case_connection' => 'Chapman struggled with poor health and poverty after separating from her husband. Her murder increased fear throughout London\'s East End.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Elizabeth Stride',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 44,
                            'occupation' => 'Charwoman',
                            'education' => null,
                            'location' => 'Whitechapel, London, England',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 30, 1888',
                            'case_connection' => 'Originally from Sweden, Stride was murdered during the "Double Event." Many investigators believe the killer was interrupted before further injuries could be inflicted.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Catherine Eddowes',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 46,
                            'occupation' => 'Casual Worker',
                            'education' => null,
                            'location' => 'Whitechapel, London, England',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 30, 1888',
                            'case_connection' => 'Killed less than an hour after Elizabeth Stride during the event later known as the "Double Event."',
                            'legacy' => 'Her murder became one of the central cases in the historic Whitechapel investigation.',
                            'image' => null,
                        ],
                        [
                            'name' => 'Mary Jane Kelly',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 25,
                            'occupation' => 'Prostitute',
                            'education' => null,
                            'location' => 'Whitechapel, London, England',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'November 9, 1888',
                            'case_connection' => 'The youngest of the five canonical victims and the only one killed indoors. She is generally regarded as Jack the Ripper\'s final canonical victim.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],

                    'wounded' => [],
                ])
            ],

            // 4th case - John Wayne Gacy
            [
                'killer_id' => 4,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'Timothy Jack McCoy',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 3, 1972',
                            'case_connection' => 'Considered John Wayne Gacy\'s first known murder victim after spending the night at Gacy\'s home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'John Butkovich',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Mechanic',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 31, 1975',
                            'case_connection' => 'An employee of Gacy who disappeared after confronting him over unpaid wages.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Darrell Julius Samson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'April 6, 1976',
                            'case_connection' => 'Last seen alive after leaving home. His remains were later identified among Gacy\'s victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Randall Wayne Reffett',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 14, 1976',
                            'case_connection' => 'One of Gacy\'s youngest identified victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Samuel G. Dodd Stapleton',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 14,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 14, 1976',
                            'case_connection' => 'Disappeared alongside Randall Reffett. Both boys were later identified among Gacy\'s victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Michael Lawrence Bonnin',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 3, 1976',
                            'case_connection' => 'Abducted while walking to a train station and later identified through dental records.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'William Huey Carroll Jr.',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 13, 1977',
                            'case_connection' => 'A teenager who disappeared after leaving home and was later identified as one of Gacy\'s victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'James Byron Haakenson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Saint Paul, Minnesota',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'August 5, 1976',
                            'case_connection' => 'Ran away from home before eventually encountering Gacy.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Rick Louis Johnston',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'August 6, 1976',
                            'case_connection' => 'Disappeared shortly after James Haakenson. Both were later identified among Gacy\'s victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Kenneth Ray Parker',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 24, 1976',
                            'case_connection' => 'One of several teenage boys murdered by Gacy during 1976.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Michael M. Marino',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 14,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 24, 1976',
                            'case_connection' => 'The youngest positively identified victim found beneath Gacy\'s house.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'William George Bundy',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 26, 1976',
                            'case_connection' => 'Worked in construction and was later identified through forensic evidence.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Francis Wayne Alexander',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Early 1977',
                            'case_connection' => 'One of Gacy\'s employees who disappeared after working for him.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Gregory John Godzik',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 12, 1976',
                            'case_connection' => 'Worked briefly for Gacy before disappearing.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'John Alan Szyc',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 20, 1977',
                            'case_connection' => 'Accepted a job offer from Gacy shortly before disappearing.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Jon Steven Prestidge',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'March 1977',
                            'case_connection' => 'One of several young men employed by Gacy who never returned home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Matthew Walter Bowman',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 5, 1977',
                            'case_connection' => 'Disappeared after accepting work with Gacy.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Robert Edward Gilroy Jr.',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 15, 1977',
                            'case_connection' => 'Last seen alive while traveling to visit a friend.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'John Antheney Mowery',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 25, 1977',
                            'case_connection' => 'Accepted temporary construction work shortly before disappearing.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Russell Lloyd Nelson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 17, 1977',
                            'case_connection' => 'Worked for Gacy and was later identified among the victims recovered from the property.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Robert David Winch',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 16,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'November 10, 1977',
                            'case_connection' => 'A teenage student who disappeared while walking home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Tommy Joseph Boling',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 1978',
                            'case_connection' => 'One of the final identified victims murdered before Gacy\'s arrest.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'David Paul Talsma',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 9, 1978',
                            'case_connection' => 'Accepted a construction job from Gacy shortly before disappearing.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'William Wayne Kindred',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'February 16, 1976',
                            'case_connection' => 'A young laborer whose remains were later recovered from Gacy\'s property.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Timothy David O\'Rourke',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 1977',
                            'case_connection' => 'Worked for Gacy before disappearing without a trace.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Frank William Landingin',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'November 4, 1978',
                            'case_connection' => 'One of Gacy\'s last known victims before the investigation intensified.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'James Mazzara',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Late 1978',
                            'case_connection' => 'Disappeared after accepting temporary work from Gacy.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Robert Jerome Piest',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Des Plaines, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 11, 1978',
                            'case_connection' => 'His disappearance led investigators to Gacy\'s home.',
                            'legacy' => 'The investigation into his disappearance ultimately exposed Gacy\'s murders.',
                            'image' => null,
                        ],
                        [
                            'name' => 'Unknown',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => '17-21',
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Unknown',
                            'case_connection' => 'One of several victims whose identity remains unknown despite extensive forensic investigations.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Unknown',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => '17-22',
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Unknown',
                            'case_connection' => 'Human remains recovered from Gacy\'s property that have not yet been conclusively identified.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Unknown',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => '15-24',
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Unknown',
                            'case_connection' => 'Believed to have been a young male victim murdered by John Wayne Gacy.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Unknown',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => '23-30',
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Unknown',
                            'case_connection' => 'Recovered remains have not yet been matched to a confirmed identity.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Unknown',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => '14-18',
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Chicago, Illinois',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'Unknown',
                            'case_connection' => 'One of the unidentified victims whose identity remains an active subject of historical forensic research.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],

                    'wounded' => [],
                ])
            ],

            // 5th case - Jeffrey Dahmer
            [
                'killer_id' => 5,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'Steven Mark Hicks',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Hitchhiker',
                            'education' => null,
                            'location' => 'Bath Township, Ohio',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 18, 1978',
                            'case_connection' => 'Jeffrey Dahmer\'s first victim. Hicks accepted a ride from Dahmer before being killed at his family home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Steven Walter Tuomi',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 25,
                            'occupation' => 'Hotel Guest',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 1987',
                            'case_connection' => 'Met Dahmer at a bar and accompanied him to a hotel. Dahmer later claimed to have no memory of killing him.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'James Edward Doxtator',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 14,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'January 16, 1988',
                            'case_connection' => 'A Native American teenager lured with money in exchange for posing for photographs.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Richard Guerrero',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Factory Worker',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'March 24, 1988',
                            'case_connection' => 'Met Dahmer outside a gay bar before becoming one of his victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Anthony Lee Sears',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 24,
                            'occupation' => 'Model',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'March 25, 1989',
                            'case_connection' => 'An aspiring model whose remains were among the first Dahmer preserved.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Raymond Lamont Smith (a.k.a. Ricky Beeks)',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 32,
                            'occupation' => 'Sex Worker',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 20, 1990',
                            'case_connection' => 'His murder marked the beginning of Dahmer\'s final killing spree.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Edward Warren Smith',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 27,
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 14, 1990',
                            'case_connection' => 'Met Dahmer in a bar before accompanying him home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Ernest Marquez Miller',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Dancer',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 2, 1990',
                            'case_connection' => 'A Chicago native who was offered money to pose for photographs.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'David Courtney Thomas',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 24, 1990',
                            'case_connection' => 'Met Dahmer shortly before disappearing. His remains were later recovered.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Curtis Durrell Straughter',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'February 18, 1991',
                            'case_connection' => 'One of Dahmer\'s youngest victims, approached near a bus stop.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Errol Lindsey',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 19,
                            'occupation' => 'Laborer',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'April 7, 1991',
                            'case_connection' => 'One of the victims subjected to Dahmer\'s attempts to create a compliant "living zombie."',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Tony Anthony Hughes',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 31,
                            'occupation' => 'Model',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 24, 1991',
                            'case_connection' => 'A deaf and non-verbal man who met Dahmer at a local bar.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Konerak Sinthasomphone',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 14,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'May 27, 1991',
                            'case_connection' => 'Escaped Dahmer briefly before being returned to his apartment by police after Dahmer falsely claimed to be his partner.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Matt Cleveland Turner',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'June 30, 1991',
                            'case_connection' => 'Traveling through Milwaukee when he encountered Dahmer.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Jeremiah Benjamin Weinberger',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 23,
                            'occupation' => 'Unknown',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 5, 1991',
                            'case_connection' => 'Visited Milwaukee from Chicago and met Dahmer shortly before disappearing.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Oliver Joseph Lacy',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 24,
                            'occupation' => 'Bodybuilder',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 15, 1991',
                            'case_connection' => 'A bodybuilder whom Dahmer met on the street before luring him to his apartment.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Joseph Arthur Bradehoft',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 25,
                            'occupation' => 'Construction Worker',
                            'education' => null,
                            'location' => 'Milwaukee, Wisconsin',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'July 19, 1991',
                            'case_connection' => 'Jeffrey Dahmer\'s final victim before his arrest three days later.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],

                    'wounded' => [],
                ])
            ],

            // 6th case - Coral Eugene Watts
            [
                'killer_id' => 6,
                'count' => json_encode([
                    'killed' => [
                        [
                            'name' => 'Yolanda Washington',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 17,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'December 1979',
                            'case_connection' => 'Believed to be one of Coral Eugene Watts\' earliest confirmed victims. She disappeared while walking home.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Judith Lynn Miller',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'September 11, 1980',
                            'case_connection' => 'A teenage girl attacked while walking through her neighborhood. Her murder was later linked to Watts.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Nancy Jo Baird',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'Office Worker',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => 'October 1980',
                            'case_connection' => 'Disappeared after leaving work. Her body was later discovered and connected to Watts.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Debra Jackson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 32,
                            'occupation' => 'Nurse',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1981',
                            'case_connection' => 'Killed while walking through her neighborhood during Watts\' series of random attacks.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Linda Lee Sparks',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 18,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1981',
                            'case_connection' => 'One of several young women targeted while alone in public.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Sonja Johnson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 14,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1981',
                            'case_connection' => 'A young teenager murdered during Watts\' crime spree in Houston.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Maria Hernandez',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'Retail Worker',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'Attacked after leaving work. She was initially believed to have survived but later died from the assault.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Mignon DuFree',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'High School Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'A high school student who became one of Watts\' youngest confirmed victims.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Yolanda Johnson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 21,
                            'occupation' => 'College Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'Killed while walking alone. Her case was later attributed to Coral Eugene Watts.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Jacqueline Lamotte',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 15,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'One of several teenage girls murdered during Watts\' attacks.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Cindy Hudspeth',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 20,
                            'occupation' => 'College Student',
                            'education' => null,
                            'location' => 'Houston, Texas',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'Disappeared while walking alone. Her murder remained unsolved until Watts confessed to multiple killings.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Diane Wilder',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 27,
                            'occupation' => 'Secretary',
                            'education' => null,
                            'location' => 'Detroit, Michigan',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'One of the victims killed after Watts relocated to Michigan.',
                            'legacy' => null,
                            'image' => null,
                        ],
                        [
                            'name' => 'Kimberly Nelson',
                            'birth_date' => null,
                            'death_date' => null,
                            'age' => 22,
                            'occupation' => 'Student',
                            'education' => null,
                            'location' => 'Detroit, Michigan',
                            'interests' => [],
                            'aspirations' => null,
                            'about' => null,
                            'case_date' => '1982',
                            'case_connection' => 'Among the final confirmed victims linked to Coral Eugene Watts before his arrest.',
                            'legacy' => null,
                            'image' => null,
                        ],
                    ],

                    'wounded' => [],
                ])
            ],
        ]);
    }
}
